setup file project
jalal1379/set-hello pull request #1
Opened 2023-05-31 13:36 UTC by jalal1379

I bring changes that the code reviewer want.

- [ ] Add HTML file.
- [ ] Add CSS file.
- [ ] Add linters.

2023-05-31 21:30 UTC, Alusp requested changes
Hi @jalal1379, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![close](https://media.giphy.com/media/3ogwFKH8NPzxxIl2Cc/giphy.gif)

## Highlights

- [ ] Descriptive PR summary :white_check_mark: 
- [ ] All Linters Checks Passing :white_check_mark: 
- [ ] Use Professional Readme :white_check_mark: 
- [ ] Correct Github flow :white_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

- [ ] Please kindly Ensure that you always use the previous PR which the First Reviewer requested on in the future to avoid inconsistency.
- [ ] Please add the Test.md file and ignore it in the .gitignore file as it is part of the project requirement as you can see in the image below: :arrow_down: 

![TestMdfile](https://github.com/jalal1379/set-hello/assets/43528594/c87a5cfd-b4e8-4915-855f-169957c7b00f)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 21:30 UTC, Alusp commented on README.md
> +-->
- [ ] Great job in implementing the changes :clap: Please this and all other commented words in your Readme as they are meant to be instructions on how to use the Readme file. :+1:

2023-05-31 21:30 UTC, Alusp commented on README.md
> +  <br/>
- [ ] Please remove this section if you do not have a logo as your img src is not pointing to any image in your project. However, if you want to use a logo, Kindly ensure that the src in the img tag is pointing to the image directory. :+1:

2023-05-31 21:30 UTC, Alusp commented on README.md
> +
- [ ] Please replace this word `SET hello` to `Hello Microverse` in order to conform with the correct Project title, By adding the correct project title in your README file, you enhance the clarity, searchability, and identification of your project. It helps differentiate your project, manage user expectations, and ensure consistency in branding and communication. :smiley:

2023-06-05 18:00 UTC, stanleySimeon requested changes
# Hi @jalal1379, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media4.giphy.com/media/fxwrhUeEyFkAKgwxqr/giphy-downsized.gif?cid=29caca75bir95ebh94w4htj59zbh4h641otd5h1lu2cnsgyi&ep=v1_gifs_search&rid=giphy-downsized.gif&ct=g)

## Highlights
- Correct use of Gitflow ✔️
- Linter checks are passed ✔️
- Good PR description ✔️
- Meaningful commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- adding `test.md` file

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-05 18:00 UTC, stanleySimeon commented on index.html
> +    <div class="hello">Hello world</div>
Great work on implementing this block, but According to the project's requirements I suggest you use the `h1` tag instead of a `div` tag for the heading and note that the `h1` tag should have the text `Hello Microverse`. 😄 

<img width="688" alt="Screenshot 2023-06-05 at 1 57 50 PM" src="https://github.com/jalal1379/set-hello/assets/91237525/fcb72d2a-13c9-4037-912a-be3d6aaa8a0d">

2023-06-05 19:13 UTC, aamirkhan2478 approved these changes
Hi @jalal1379 , 

![GIF](https://www.funimada.com/assets/images/cards/big/congrats-7.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ You used Gitflow correctly :+1: 
✅ No linter error :+1: 
✅ Good commit messages :+1: 
✅ Good descriptive PR :+1: 
✅ Well done :clap: you did all changes given by the previous reviewer :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-05 19:16 UTC, merged